spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:4000/family_bonding_db?useSSL=true&enabledTLSProtocols=TLSv1.2,TLSv1.3}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server
server.port=${PORT:8080}
server.servlet.context-path=/family-bonding-api
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Logging
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=ERROR
